server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    data: classpath:data.sql
    schema: classpath:schema.sql
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:defaultZone: http://localhost:8671/eureka
  instance:
    prefer-ip-address: true #表示注册到服务中心
    metadata-map:
      data: "自定义的数据"
    virtual-host-name: microservice-provider-user
logging:
  level:
      root: info
      org:
        springframework:
          cloud:
            sleuth: debug
