spring:
  application:
    name: eurekademo-ha

security:
   basic:
     enabled: true
   user:
     name: user
     password: 123456


---
server:
  port: 8761
eureka:
  instance:
    hostname: peer1  #指定当profile为peer1时，主机名为peer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka  #指定注册到peer2上

spring:
  profiles: peer1 #指定profile为peer1

---
spring:
     profiles: peer2
server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka
  instance:
    hostname: peer2